src/features/api/apiSlice.ts
src/features/game/GameSlice.ts

include credentials

---

src/app/GameStateHandler.tsx
src/game/elements/cardDisplay/CardDisplay.module.css
src/game/elements/cardDisplay/CardDisplay.tsx
src/game/elements/optionsMenu/OptionsMenu.tsx
src/game/elements/playerHandCard/PlayerHandCard.module.css
src/game/elements/playerHandCard/PlayerHandCard.tsx
src/game/zones/banishZone/BanishZone.tsx
src/game/zones/graveyardZone/GraveyardZone.tsx
src/game/zones/pitchZone/PitchZone.tsx

A couple of small fixes:
Closes #64 
Closes #62

Small fixes

---

src/game/elements/cardDisplay/CardDisplay.module.css
src/game/elements/cardDisplay/CardDisplay.tsx
src/game/elements/endGameMenuOptions/EndGameMenuOptions.module.css
src/game/elements/endGameMenuOptions/EndGameMenuOptions.test.tsx
src/game/elements/endGameMenuOptions/EndGameMenuOptions.tsx
src/game/elements/endGameScreen/EndGameScreen.module.css
src/game/elements/endGameScreen/EndGameScreen.test.tsx
src/game/elements/endGameScreen/EndGameScreen.tsx
src/game/elements/endGameStats/EndGameStats.tsx
src/game/elements/playerHandCard/PlayerHandCard.module.css
src/game/elements/playerHandCard/PlayerHandCard.tsx

all seven colours same as on legacy client

---

src/app/GameStateHandler.tsx
src/game/elements/actionPointDisplay/ActionPointDisplay.tsx
src/game/elements/eventsHandler/EventsHandler.module.css
src/game/elements/eventsHandler/EventsHandler.tsx

Fix double toast renders
A few performance improvements
More toasts
Remove some unneeded things.

Double render fixes

---

package-lock.json
package.json
src/routes/game/components/zones/permanentsZone/PermanentsZone.module.css
src/routes/game/components/zones/permanentsZone/PermanentsZone.tsx
tsconfig.json

Stacking permanents

---

index.html
src/routes/game/components/elements/chatCardDetail/ChatCardDetail.module.css
src/routes/game/components/elements/chatCardDetail/ChatCardDetail.test.tsx
src/routes/game/components/elements/chatCardDetail/ChatCardDetail.tsx
src/routes/game/play/Play.tsx

Fixes https://github.com/Talishar/Talishar-FE/issues/93

Add Component for card detail on hover

---

src/app/ParseGameState.ts

Small fix for patreon and contributor chat images not appearing on react FE.
We will eventually be redoing the whole chat

replace chat log messages

---

index.html

Fix failure to reload page on prod

---

src/app/GameStateHandler.tsx
src/hooks/useKnownSearchParams.tsx
src/index.tsx
src/routes.tsx
src/routes/index/Index.tsx

Added route guards that force redirect if you have 
- On '/', gameName & playerID redirects to game/play (previously existed anyway)
- On 'game/play', if gameName & playerID doesn't exist redirect them back to the index.
Added useKnownSearchParams. Where we register any searchParams we're going to use and we can easily set and access the values without using the native dom window.

Add route guards and useKnownSearchParams hook

---

src/routes/game/components/elements/cardPortal/CardPortal.tsx
src/routes/game/lobby/Lobby.module.css
src/routes/game/lobby/Lobby.tsx
src/routes/game/lobby/components/deck/Deck.module.css
src/routes/game/lobby/components/deck/Deck.tsx
src/routes/game/lobby/components/equipment/Equipment.module.css
src/routes/game/lobby/components/equipment/Equipment.tsx
src/routes/game/lobby/components/stickyFooter/StickyFooter.module.css
src/routes/game/lobby/components/stickyFooter/StickyFooter.tsx

Put a container in the lobby so it doesn't spew out super wide.
Hero names stick to the top of the lobby container.
CardPortal / CardPopUp when hovering or long pressing on an image

Lobby contained

---

src/routes/game/components/elements/phaseTracker/PhaseTracker.module.css
src/routes/game/components/elements/phaseTracker/__snapshots__/PhaseTracker.test.tsx.snap
src/routes/game/components/elements/phaseTrackerWidget/PhaseTrackerWidget.module.css
src/routes/game/components/elements/phaseTrackerWidget/PhaseTrackerWidget.tsx
src/routes/game/components/elements/phaseTrackerWidget/__snapshots__/PhaseTrackerWidget.test.tsx.snap

fix phase tracker widget

---

src/interface/API/GetLobbyRefresh.php.ts
src/routes/game/components/elements/phaseTracker/PhaseTracker.module.css
src/routes/game/components/elements/phaseTracker/__snapshots__/PhaseTracker.test.tsx.snap
src/routes/game/components/elements/phaseTrackerWidget/PhaseTrackerWidget.module.css
src/routes/game/components/elements/phaseTrackerWidget/PhaseTrackerWidget.tsx
src/routes/game/components/elements/phaseTrackerWidget/__snapshots__/PhaseTrackerWidget.test.tsx.snap
src/routes/game/join/Join.tsx
src/routes/game/lobby/Lobby.tsx

Can now join a game, just about.
Relies on https://github.com/Talishar/Talishar/pull/258 being pushed to prod.

Join game flow

---

src/interface/API/CreateGame.php.ts
src/interface/API/GetLobbyInfo.php.ts
src/interface/API/GetLobbyRefresh.php.ts
src/interface/API/JoinGame.php.ts
src/routes/game/lobby/Lobby.module.css
src/routes/game/lobby/Lobby.tsx
src/routes/game/lobby/components/matchups/Matchups.module.css
src/routes/game/lobby/components/matchups/Matchups.tsx
src/routes/game/lobby/mockdata.json
src/routes/game/lobby/validation.ts
src/routes/index/components/gameList/GameList.tsx

Closes #128
Handle fabrary sideboarding.

Add quiver + allow submission of fabrary sideboards

---

src/routes/game/create/CreateGame.tsx
src/routes/game/lobby/Lobby.module.css
src/routes/game/lobby/Lobby.tsx
src/routes/game/lobby/components/chooseFirstTurn/ChooseFirstTurn.tsx
src/routes/game/lobby/components/deck/Deck.module.css
src/routes/game/lobby/components/equipment/Equipment.module.css
src/routes/game/lobby/components/lobbyChat/LobbyChat.module.css
src/routes/game/lobby/components/matchups/Matchups.module.css
src/routes/game/lobby/components/updateHandler/SideboardUpdateHandler.tsx

Lobby scroll

---

src/routes/game/create/CreateGame.tsx
src/routes/game/create/CreateGameErrors.tsx
src/routes/game/create/validationSchema.ts
src/routes/game/join/Join.tsx
src/routes/game/join/validationSchema.ts
src/routes/index/Index.module.css
src/routes/index/components/gameList/GameList.module.css
src/routes/user/login/components/LoginForm.tsx

Favorite decks

---

src/app/ParseGameState.ts
src/features/Card.ts
src/routes/game/components/elements/chainLinkSummary/ChainLinkSummary.test.tsx
src/routes/game/components/elements/countersOverlay/CountersOverlay.module.css
src/routes/game/components/elements/countersOverlay/CountersOverlay.tsx
src/routes/game/components/elements/endGameScreen/EndGameScreen.test.tsx
src/utils/TestUtils.tsx

cards faceup or facedown

---

src/constants.ts
src/features/api/apiSlice.ts
src/routes/game/components/elements/gemSlider/GemSlider.tsx
src/routes/index/Index.tsx
src/routes/index/components/filter/Filter.tsx
src/routes/index/components/filter/constants.ts
src/routes/index/components/filter/index.tsx
src/routes/index/components/gameList/GameList.tsx
src/routes/index/components/gameList/index.tsx
src/routes/index/components/inProgressGame/InProgressGame.module.css
src/routes/index/components/inProgressGame/InProgressGame.tsx
src/routes/index/components/inProgressGame/index.tsx
src/routes/index/components/openGame/OpenGame.module.css
src/routes/index/components/openGame/OpenGame.tsx
src/routes/index/components/openGame/index.tsx
src/routes/user/login/components/ForgottenPasswordForm.tsx
src/routes/user/login/components/LoginForm.tsx
src/routes/user/login/components/SignUpForm.tsx
src/routes/user/login/components/validation.ts

Oh none of these improvements are actually issues.
Skeleton for forgotten password page.
Some refactoring to make smaller components - need to do a lot more of this so the project is much nicer and more readable.
Added a filter for filtering games by hero.
https://user-images.githubusercontent.com/5060535/219933936-ed69aba5-8fcf-47ee-ba0b-c69268d7e596.mov

Password recovery

---

src/app/GameStateHandler.tsx
src/interface/GameLocationState.ts
src/routes/game/components/elements/optionsMenu/OptionsMenu.tsx
src/routes/game/components/elements/turnWidget/TurnWidget.tsx
src/routes/game/create/CreateGame.tsx
src/routes/game/join/Join.tsx
src/routes/game/lobby/Lobby.tsx
src/routes/game/lobby/components/updateHandler/SideboardUpdateHandler.tsx

Was not on the issues list but this PR fixes the problem of:
Refreshing the page will make you lose your game in progress.

Refresh game

---

src/app/GameStateHandler.tsx
src/features/game/GameSlice.ts
src/routes/game/components/elements/playerPrompt/PlayerPrompt.module.css
src/routes/game/lobby/components/updateHandler/SideboardUpdateHandler.tsx
src/routes/index/components/gameList/GameList.tsx

Closes #185 (but need to double and triple check it)

attempt to fix long poll

---

src/routes/game/components/combatChain/CombatChain.module.css
src/routes/game/components/elements/optionsMenu/OptionsMenu.tsx
src/routes/game/components/elements/playerPrompt/PlayerPrompt.module.css
src/routes/game/components/elements/playerPrompt/PlayerPrompt.tsx
src/routes/game/components/elements/playmat/Playmat.module.css
src/routes/game/components/gridBoard/GridBoard.module.css
src/routes/game/components/zones/activeLayersZone/ActiveLayersZone.module.css
src/routes/game/create/CreateGame.module.css
src/routes/index/Index.module.css
src/routes/index/components/formatList/FormatList.module.css
src/routes/index/components/formatList/FormatList.tsx
src/routes/index/components/formatList/index.tsx
src/routes/index/components/gameList/GameList.module.css
src/routes/index/components/gameList/GameList.tsx
src/routes/index/components/gameList/__snapshots__/GameList.test.tsx.snap
src/routes/index/components/openGame/OpenGame.tsx

Improve the main menu a little bit and the active layers box a bit larger

Categories main menu

---

src/routes/game/components/elements/pitchDisplay/PitchDisplay.module.css
src/routes/game/components/zones/pitchZone/PitchZone.module.css
src/routes/game/components/zones/pitchZone/PitchZone.tsx
src/routes/game/components/zones/pitchZone/index.tsx

Closes #118
https://gfycat.com/grimtinybluegill

The stack is even animated

---

src/app/Store.ts
src/appConstants.ts
src/features/api/apiSlice.ts
src/features/game/GameSlice.ts
src/features/options/constants.ts
src/features/options/optionsSlice.ts
src/hooks/useSetting.tsx
src/interface/API/ProcessInputAPI.ts
src/interface/GameOptions.ts
src/routes/game/components/elements/menu/FullControlToggle/FullControlToggle.tsx
src/routes/game/components/elements/menu/HideModalsToggle/HideModalsToggle.tsx
src/routes/game/components/elements/menu/Menu.tsx
src/routes/game/components/elements/optionsMenu/OptionsMenu.tsx
src/routes/game/components/elements/optionsMenu/OptionsSettings/OptionsSettings.module.css
src/routes/game/components/elements/optionsMenu/OptionsSettings/OptionsSettings.tsx
src/routes/game/components/elements/optionsMenu/OptionsSettings/index.tsx
src/routes/game/components/zones/activeLayersZone/ActiveLayersZone.tsx

Options slice

---

src/routes/game/components/elements/chainLinkSummary/ChainLinkSummary.tsx
src/routes/game/components/elements/chatInput/ChatInput.tsx
src/routes/game/components/elements/endGameScreen/EndGameScreen.tsx
src/routes/game/components/elements/optionsMenu/OptionsMenu.tsx
src/routes/game/components/elements/playmat/Playmat.module.css
src/routes/game/components/elements/playmat/Playmat.tsx
src/routes/game/components/zones/activeLayersZone/ReorderLayers/ReorderLayers.tsx
src/routes/game/components/zones/activeLayersZone/reorderLayers/ReorderLayers.tsx
src/routes/game/components/zones/cardListZone/CardListZone.tsx
src/routes/game/components/zones/handZone/HandZone.tsx
src/routes/game/components/zones/playerHand/PlayerHand.tsx
src/routes/game/lobby/Lobby.tsx
src/routes/game/lobby/components/chooseFirstTurn/ChooseFirstTurn.tsx
src/routes/game/lobby/components/matchups/Matchups.tsx
src/routes/game/lobby/components/updateHandler/SideboardUpdateHandler.tsx

Bugfix: Small change as the playmats weren't aligned properly.
Chore: Also took the chance to refactor "getGameInfo" instead of the long selector for it, and use shallowEqual to stop uneeded rerenders.

Playmat fix

---

src/app/ParseGameState.ts
src/appConstants.ts
src/features/GameState.ts
src/features/game/GameSlice.ts
src/routes/game/components/activeEffects/ActiveEffects.tsx
src/routes/game/components/elements/endGameMenuOptions/EndGameMenuOptions.tsx
src/routes/game/components/elements/optionsMenu/OptionsMenu.tsx
src/routes/game/components/zones/LandmarkZone/LandmarkZone.module.css
src/routes/game/components/zones/LandmarkZone/LandmarkZone.test.tsx
src/routes/game/components/zones/LandmarkZone/LandmarkZone.tsx
src/routes/game/components/zones/LandmarkZone/index.tsx
src/routes/index/Index.tsx
src/routes/user/login/components/ForgottenPasswordForm.tsx
src/routes/user/login/components/SignUpForm.tsx
src/routes/user/profile/index.tsx
src/routes/user/profile/profile.module.css
vite.config.ts

Closes #173 (the landmark is in the effects column)
Closes #22 
Closes #144
Closes #211 most of the issues have been addressed

Fixes on 13th March

---

src/routes.tsx
src/routes/game/create/CreateGame.tsx

Load fabdb and fabrary

---

src/features/GameState.ts
src/routes/game/components/zones/activeLayersZone/ActiveLayersZone.module.css
src/routes/game/components/zones/activeLayersZone/ActiveLayersZone.tsx
src/routes/game/components/zones/banishZone/BanishZone.tsx
src/routes/game/components/zones/deckZone/DeckZone.tsx
src/routes/game/components/zones/graveyardZone/GraveyardZone.tsx
src/routes/game/components/zones/permanentsZone/PermanentsZone.module.css

- scrollbar on permanents
- active layers target
- Show zone counts by default

permantnes scroll bar

---

src/hooks/useAuth.tsx
src/routes/game/lobby/components/matchups/Matchups.module.css
src/routes/user/login/components/LoginForm.tsx

- refetch favourite decks on login or auth success
- comment out deck refetch on useAuth hook

refetch favourite decks on login

---

src/routes/game/components/combatChain/CombatChain.module.css
src/routes/game/components/elements/healthDisplay/HealthDisplay.module.css
src/routes/game/components/elements/passTurnDisplay/PassTurnDisplay.module.css
src/routes/game/components/elements/playmat/Playmat.module.css
src/routes/game/components/elements/playmat/Playmat.tsx
src/routes/game/components/elements/turnWidget/TurnWidget.module.css

Changes:
- combat chain + health things are smaller
- combat chain background removed, swapped to dark transparent overlay
- playmats brighter
- replaced Aria playmat with Pits
Before:
After:

Reductions to the combat chain, Pits playmat, brighter playmats!

---

src/routes/game/components/elements/optionsMenu/OptionsMenu.tsx

Implement revert to previous turn

---

src/routes/game/components/elements/optionsMenu/OptionsMenu.tsx

Fix revert to start turn

---

src/interface/API/GetFavoriteDecks.php.ts
src/routes/game/create/CreateGame.tsx

Use remembered game settings

---

src/components/header/Header.tsx

We are launching new roguelike experience so we will disable access to it while they get it all fixed up

Disable link to roguelike with a tip saying coming soon

---

src/app/ParseGameState.ts
src/features/options/cardBacks.ts
src/routes/game/components/elements/cardDisplay/CardDisplay.module.css
src/routes/game/components/elements/optionsMenu/OptionsMenu.tsx
src/routes/game/components/elements/optionsMenu/OptionsSettings/OptionsSettings.module.css
src/routes/game/components/elements/optionsMenu/OptionsSettings/OptionsSettings.tsx
src/routes/game/components/elements/playmat/Playmat.tsx

attempt getCosmetics query

---

src/appConstants.ts
src/features/api/apiSlice.ts
src/routes.tsx
src/routes/user/profile/index.tsx
src/routes/user/profile/linkpatreon/index.tsx
src/routes/user/profile/linkpatreon/linkPatreon.tsx

Closes #333 
Partial stuff for patreon login

Not valid JSON displayed

---

src/features/api/apiSlice.ts
src/routes/game/components/elements/cardDisplay/CardDisplay.module.css
src/routes/game/components/elements/cardPortal/CardPortal.module.css
src/routes/game/components/elements/chatBox/ChatBox.module.css
src/routes/game/components/elements/countersOverlay/CountersOverlay.module.css
src/routes/game/components/elements/currentAttack/CurrentAttack.module.css
src/routes/game/components/elements/phaseTracker/PhaseTracker.module.css
src/routes/game/components/elements/playerPrompt/PlayerPrompt.module.css
src/routes/game/components/zones/LandmarkZone/LandmarkZone.module.css
src/routes/game/components/zones/activeLayersZone/ActiveLayersZone.module.css
src/routes/game/components/zones/activeLayersZone/ActiveLayersZone.tsx
src/routes/game/components/zones/arsenalZone/ArsenalZone.module.css
src/routes/game/components/zones/banishZone/BanishZone.module.css
src/routes/game/components/zones/cardListZone/CardListZone.module.css
src/routes/game/components/zones/chestEqZone/ChestEqZone.module.css
src/routes/game/components/zones/deckZone/DeckZone.module.css
src/routes/game/components/zones/feetEqZone/FeetEqZone.module.css
src/routes/game/components/zones/glovesEqZone/GlovesEqZone.module.css
src/routes/game/components/zones/graveyardZone/GraveyardZone.module.css
src/routes/game/components/zones/handZone/HandZone.module.css
src/routes/game/components/zones/headEqZone/HeadEqZone.module.css
src/routes/game/components/zones/heroZone/HeroZone.module.css
src/routes/game/components/zones/permanentsZone/PermanentsZone.module.css
src/routes/game/components/zones/pitchZone/PitchZone.module.css
src/routes/game/components/zones/playerHand/PlayerHand.module.css
src/routes/game/components/zones/weaponLZone/WeaponLZone.module.css
src/routes/game/components/zones/weaponRZone/WeaponRZone.module.css
src/routes/game/components/zones/zoneCountsZone/ZoneCounts.module.css

Reverts Talishar/Talishar-FE#336

Revert "Tweak"

---

src/features/api/apiSlice.ts

Fix the annoying error when you submit stuff and the response is just empty

Suppress error

---

src/routes/game/components/zones/activeLayersZone/ReorderLayers/ReorderLayers.tsx

Fix jankiness in layer ordering
Closes #338 
Closes #295 (hopefully)

Layer orders

---

src/features/api/apiSlice.ts
src/interface/API/UserProfileAPI.php.ts
src/routes/game/components/elements/chatBox/ChatBox.module.css
src/routes/game/components/elements/chatBox/ChatBox.tsx
src/routes/game/components/elements/chatInput/ChatInput.module.css
src/routes/game/components/elements/playerInputPopUp/PlayerInputPopUp.module.css
src/routes/game/components/elements/playerInputPopUp/PlayerInputPopUp.tsx
src/routes/game/components/elements/playerInputPopUp/components/OtherInput.tsx
src/routes/game/components/elements/turnWidget/TurnWidget.module.css
src/routes/game/components/opponentBoardGrid/OpponentBoardGrid.tsx
src/routes/game/components/zones/permanentsZone/PermanentsZone.module.css
src/routes/game/components/zones/zoneCountsZone/ZoneCounts.module.css
src/routes/user/profile/index.tsx
src/utils/ParseEscapedString.ts

Parse cards

---

src/app/GameStateHandler.tsx
src/app/ParseGameState.ts
src/mocks/api/GetNextTurn3.ts
src/routes/game/components/elements/chatBox/ChatBox.tsx
src/routes/game/components/zones/arsenalZone/ArsenalZone.tsx

Closes #215 
Add some mocking and stuff, using special game number 101 and a mock, won't cause the long ping, so it's good if you want to fake some state in the backend (like a frozen arsenal) to check it's working.
Closes #39 
Closes #219 (this actually closed ages ago)
Closes #150 (long time ago)

Mocks and chat improvements

---

src/routes/game/components/elements/cardPortal/CardPortal.module.css
src/routes/game/components/elements/playerHandCard/PlayerHandCard.tsx
src/routes/game/components/zones/playerHand/PlayerHand.module.css
src/routes/game/components/zones/playerHand/PlayerHand.tsx

Reverse layer of cards

---

src/routes/game/lobby/Lobby.module.css
src/routes/game/lobby/Lobby.tsx
src/routes/game/lobby/components/deck/Deck.module.css
src/routes/game/lobby/components/equipment/Equipment.module.css

Sideboarding has a tab between deck and equipment

collapse sideboarding to one page for desktop

---

src/routes/user/login/components/ForgottenPasswordForm.tsx
src/routes/user/login/components/LoginForm.tsx

* Update the check for response message.
* Fix link to registration
* Add space before Privacy Policy
Closes #359

Fix Response message check

---

src/app/ExperimentalGameStateHandler.tsx
src/routes/game/components/combatChain/CombatChain.module.css
src/routes/game/components/combatChain/CombatChain.tsx
src/routes/game/components/elements/actionPointDisplay/ActionPointDisplay.module.css
src/routes/game/components/elements/actionPointDisplay/ActionPointDisplay.test.tsx
src/routes/game/components/elements/actionPointDisplay/ActionPointDisplay.tsx
src/routes/game/components/elements/cardDisplay/CardDisplay.module.css
src/routes/game/components/elements/cardPortal/CardPortal.module.css
src/routes/game/components/elements/chainLinks/ChainLinks.module.css
src/routes/game/components/elements/chainLinks/ChainLinks.tsx

Closes #369 (fixed a while ago)
Lots of small changes as suggested last week

Lots of changes

---

src/routes/game/components/elements/optionsMenu/OptionsSettings/OptionsSettings.tsx

Allow people to disable stats tracking

disable stats

---

src/errorPage.tsx
src/index.tsx
src/routes/game/components/elements/cardImage/CardImage.module.css
src/routes/game/components/elements/chatBox/ChatBox.module.css
src/routes/game/components/elements/chatBox/ChatBox.tsx
src/routes/game/components/elements/chatInput/ChatInput.tsx
src/routes/game/components/elements/optionsMenu/OptionsSettings/OptionsSettings.tsx
src/routes/game/components/elements/playerInputPopUp/components/OptInput.tsx
src/routes/game/components/zones/zoneCountsZone/ZoneCounts.tsx

Some small QOL changes and adding strictmode for dev env
Closes #371 I hope
Closes #370 just using useState and a filter.
Closes #367 (zone counts zone re-appears if there's soul or blood debt)

Prevent default

---

src/routes/game/components/zones/activeLayersZone/ActiveLayersZone.tsx
src/routes/game/components/zones/activeLayersZone/ReorderLayers/ReorderLayers.module.css
src/routes/game/components/zones/activeLayersZone/ReorderLayers/ReorderLayers.tsx

closes #383
I used the identification of normal counter. I hope it doesn't cause confusion, since in the arena it displays the count of cards.

Add reorder Trigger Identification

---

src/appConstants.ts
src/routes/index/components/gameList/GameList.module.scss
src/routes/index/components/gameList/GameList.tsx
src/routes/index/components/inProgressGame/InProgressGame.module.scss
src/routes/index/components/inProgressGame/InProgressGame.tsx

* Split all Games in Progress into their specific formats. Formats are either set by number or string, therefore validate for both
* add a small animation on hover
* closes #324

Filter games in progress into formats

---

src/app/ExperimentalGameStateHandler.tsx
src/app/ParseGameState.ts
src/features/GameState.ts
src/features/game/GameSlice.ts
src/routes/game/components/elements/cardDisplay/CardDisplay.module.css
src/routes/game/components/elements/endGameMenuOptions/EndGameMenuOptions.tsx
src/routes/game/components/elements/playerInputPopUp/PlayerInputPopUp.module.css

Closes #368 
Closes #350 (by using the old, hacky way of doing it)}
Some small tidy up for phone/portrait mode

enables full rematch

---

package-lock.json
package.json
src/interface/API/GetFavoriteDecks.php.ts
src/routes/game/create/CreateGame.module.css
src/routes/game/create/CreateGame.tsx
src/routes/game/create/validationSchema.ts

Fixes bug with only one deck, cannot select that deck.

refactor to use react-hook-form

---

src/routes/game/components/zones/arsenalZone/ArsenalZone.module.css

Fixes arsenals not appearing on chromebooks

Makes a fixed height for the arsenal zone

---

src/routes/game/components/elements/passTurnDisplay/PassTurnDisplay.tsx
src/routes/game/lobby/Lobby.tsx

modal now using portal to appear on top of everything else

---

src/routes/game/lobby/Lobby.module.css
src/routes/game/lobby/Lobby.tsx

- adds disclaimer when joining an open format game
- remove unrequired css

open format disclaimer

---

src/interface/API/GetLobbyRefresh.php.ts
src/routes/game/lobby/Lobby.tsx

This commit introduces an invite to chat popup for the game lobby

Invite chat popup for lobby

---

src/routes/game/components/board/Board.module.css
src/routes/game/components/board/Board.tsx
src/routes/game/components/combatChain/CombatChain.module.css
src/routes/game/components/combatChain/CombatChain.tsx
src/routes/game/components/elements/playerPrompt/PlayerPrompt.module.css
src/routes/game/components/elements/turnWidget/TurnWidget.module.css
src/routes/game/components/gridBoard/GridBoard.module.css
src/routes/game/components/gridBoard/GridBoard.tsx

- grabby hand
- fiddle
- move prompt to bottom
- Fix up for mobile

popout combat chain

---

src/features/game/GameSlice.ts
src/routes/game/components/combatChain/CombatChain.module.css
src/routes/game/components/combatChain/CombatChain.tsx
src/routes/game/components/gridBoard/GridBoard.module.css
src/routes/game/components/gridBoard/GridBoard.tsx
src/routes/game/components/zones/activeLayersZone/ActiveLayersZone.tsx
src/routes/game/components/zones/permanentsZone/PermanentsZone.module.css
src/routes/game/components/zones/permanentsZone/PermanentsZone.tsx
src/routes/game/components/zones/playerHand/PlayerHand.module.css

- adding a comment
- Some further tweaks
- permanents scroll
- small fix for mobile

change permanents

---

README.md
src/routes/game/components/combatChain/CombatChain.module.css
src/routes/game/components/combatChain/CombatChain.tsx
src/routes/game/components/elements/chatBox/ChatBox.module.css
src/routes/game/components/elements/chatBox/ChatBox.tsx
src/routes/game/components/elements/playerPrompt/PlayerPrompt.tsx
src/routes/game/components/zones/arsenalZone/ArsenalZone.module.css
src/routes/game/components/zones/arsenalZone/ArsenalZone.tsx

- update readme
- Add a prompt to the combat chain
- Hide new prompt on mobile
- chatbox improvements
- Prompt tidy up

combat chain player prompt

---

src/routes/game/components/elements/cardPortal/CardPortal.module.css

Check it and push it ASAP as #436 accidentally broke the mobile UI. Multiple people complained on this, i fixed it with trial and error. 
Don't worry about that @Lykae, I would like to ask you to check this out. If you would like to improve this, please free to do so. I'm not a front-end guy I don't know what i'm doing :smiling_face_with_tear:

Fix mobile UI to be able to activate weapons and play cards from arsenal

---

src/routes/game/components/elements/cardDisplay/CardDisplay.tsx
src/routes/game/components/elements/countersOverlay/CountersOverlay.tsx
src/routes/game/components/zones/activeLayersZone/ActiveLayersZone.tsx

Closes #443
Should it be the responsibility of the BE to also say it's disabled as well as restricted?

Add restricted icon for cards with "restriction"

---

src/routes/game/components/elements/countersOverlay/components/ContinuousCounters.tsx

I simply put the attack counters in front so it is in line with the card design and how we read them from left to right.

Reverse Life and Attack counters

---

src/routes/game/components/zones/playerHand/PlayerHand.tsx

support for graveyard playable cards to implement graven call

Add support for playable cards in gy

---

src/routes/game/lobby/Lobby.tsx
src/routes/game/lobby/validation.ts

Reverts Talishar/Talishar-FE#492 i need to test it properly

Revert "Kayo hands validation"

---

src/routes/game/components/elements/cardDisplay/CardDisplay.module.css
src/routes/game/components/elements/eventsHandler/EventsHandler.module.css
src/routes/game/components/elements/eventsHandler/EventsHandler.tsx
src/routes/game/components/zones/cardListZone/CardListZone.module.css

Bug Fixes 18th

---

src/interface/API/GetLobbyInfo.php.ts
src/routes/game/lobby/Lobby.tsx
src/routes/game/lobby/components/equipment/Equipment.tsx
src/routes/game/lobby/mockdata.json
src/routes/game/lobby/validation.ts

This is the sister pull request to https://github.com/Talishar/Talishar/pull/850
To avoid weird unsync issues, it's currently a bit bodgy to allow updating FE first and then remove the compat bodges after the backend is updated. I'm not sure if there's a nice way to do that in git/github but I can just make a second PR.

Better handling of modular equipments

---

src/routes/game/lobby/Lobby.tsx
src/routes/game/lobby/components/equipment/Equipment.tsx

Second part of https://github.com/Talishar/Talishar-FE/pull/540 now that the backend has been updated, since EVO013 isn't passed as legs anymore.

Better handling of modular equipments: remove compat with previous backend

---

src/app/ParseGameState.ts

Added WTE check in case we get a weapon token equipment in the future (like a token Parry Blade etc)

Future-proofing in case of weapon token equipment

---

src/routes/game/components/elements/countersOverlay/CountersOverlay.tsx
src/routes/game/components/elements/countersOverlay/components/ContinuousCounters.tsx

added a new counter for stains on Blood Spattered Vest

added logic for stain counters on blood splattered vest

---

index.html

some files were getting _ replaced with " ", so this is switching it back

fixing code referencing images when mouse over

---

src/routes/game/lobby/Lobby.tsx

This addresses an issue where there are cards that are both in inventory and the deck

Fixing inventory bug
